<a href="https://colab.research.google.com/github/nikita0517/iris_classification/blob/main/XOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [19]:
import sys

In [22]:
X=np.array([[0, 1],[1, 0],[1, 1],[0, 0]])
Y=np.array([[1],[1],[0],[0]])

In [6]:
num_i_units = 2 # Number of Input units
num_h_units = 2 # Number of Hidden units
num_o_units = 1 # Number of Output units

In [7]:
learning_rate = 0.01
# The parameter to help with overfitting.
reg_param = 0
# Maximum iterations for Gradient Descent.
max_iter = 5000
# Number of training examples
m = 4

In [8]:
np.random.seed(1)
W1 = np.random.normal(0, 1, (num_h_units, num_i_units)) # 2x2
W2 = np.random.normal(0, 1, (num_o_units, num_h_units)) # 1x2
B1 = np.random.random((num_h_units, 1)) # 2x1
B2 = np.random.random((num_o_units, 1)) # 1x1

In [9]:
W1

array([[ 1.62434536, -0.61175641],
       [-0.52817175, -1.07296862]])

In [10]:
W2

array([[ 0.86540763, -2.3015387 ]])

In [11]:
B1

array([[0.41919451],
       [0.6852195 ]])

In [12]:
B2

array([[0.20445225]])

In [13]:
def sigmoid(z, derv=False):
    if derv: return z * (1 - z)
    return 1 / (1 + np.exp(-z))

In [15]:
def forward(x, predict=False):
    a1 = x.reshape(x.shape[0], 1) 
    z2 = W1.dot(a1) + B1 
    a2 = sigmoid(z2) 
    z3 = W2.dot(a2) + B2 
    a3 = sigmoid(z3)

    if predict: return a3
    return (a1, a2, a3)

In [16]:
dW1 = 0 
dW2 = 0
dB1 = 0 
dB2 = 0 

cost = np.zeros((max_iter, 1))

In [26]:
def train(_W1, _W2, _B1, _B2): # The arguments are to bypass UnboundLocalError error
    for i in range(max_iter):
        c = 0
        
        dW1 = 0
        dW2 = 0

        dB1 = 0
        dB2 = 0
        
        for j in range(m):
            sys.stdout.write("\rIteration: {} and {}".format(i + 1, j + 1))

          
            a0 = X[j].reshape(X[j].shape[0], 1) 

            z1 = _W1.dot(a0) + _B1
            a1 = sigmoid(z1) 

            z2 = _W2.dot(a1) + _B2 
            a2 = sigmoid(z2) 

           
            dz2 = a2 - Y[j] 
            dW2 += dz2 * a1.T 

            dz1 = np.multiply((_W2.T * dz2), sigmoid(a1, derv=True)) 
            dW1 += dz1.dot(a0.T) 

            dB1 += dz1 
            dB2 += dz2 
            c = c + (-(Y[j] * np.log(a2)) - ((1 - Y[j]) * np.log(1 - a2)))
            sys.stdout.flush() 
        
        _W1 = _W1 - learning_rate * (dW1 / m) + ( (reg_param / m) * _W1)
        _W2 = _W2 - learning_rate * (dW2 / m) + ( (reg_param / m) * _W2)

        _B1 = _B1 - learning_rate * (dB1 / m)
        _B2 = _B2 - learning_rate * (dB2 / m)
        cost[i] = (c / m) + ( 
            (reg_param / (2 * m)) * 
            (
                np.sum(np.power(_W1, 2)) + 
                np.sum(np.power(_W2, 2))
            )
        )
    return (_W1, _W2, _B1, _B2)

In [27]:
W1, W2, B1, B2 = train(W1, W2, B1, B2)

Iteration: 5000 and 4

In [30]:
W1

array([[ 1.32260643, -0.42332921],
       [-1.4336158 , -1.67239068]])

In [31]:
W2

array([[ 0.25299514, -2.21317287]])

In [32]:
B1

array([[ 0.37348207],
       [-0.22080277]])

In [ ]:
B2